//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace partI.DB_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int ID_Employee { get; set; }
        public string User { get; set; }
        public string Pass { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
